// entries-wave6.mjs — Wave 6: Strengthen P, RE, CO, SY tags in overfilled tiers
// T13 Reasoning: +8 entries (P=4→12, SY=6→10)
// T12 Complexity: +3 entries (P=8→11)
// T7 Emerging: +2 entries (IN=7→9, P=11→13)

export const wave6T13 = {
  id: 'wave6-t13',
  description: 'T13 Reasoning: strengthen P and SY tags (+8 entries)',
  commit_msg: 'feat(bib): Wave 6 — add 8 reasoning entries strengthening P/SY tags in T13',
  entries: [
    {
      file: 'T13_reasoning.bib',
      type: 'article',
      key: 'Tversky1983Extensional',
      title: 'Extensional versus Intuitive Reasoning: The Conjunction Fallacy in Probability Judgment',
      author: 'Tversky, Amos and Kahneman, Daniel',
      year: '1983',
      journal: 'Psychological Review',
      volume: '90',
      number: '4',
      pages: '293--315',
      doi: '10.1037/0033-295X.90.4.293',
      abstract: 'Tversky and Kahneman demonstrate the conjunction fallacy: people systematically judge the conjunction of two events as more probable than either event alone, violating the extensional logic of probability theory. In the famous Linda problem, subjects rate "Linda is a feminist bank teller" as more probable than "Linda is a bank teller," despite the conjunction rule. This finding reveals that human reasoning often relies on intuitive representativeness heuristics rather than extensional (set-theoretic) logic, with broad implications for rationality, judgment under uncertainty, and the architecture of human inference. Directly grounds HUMMBL Perspective (P) and Inversion (IN) operators by showing how cognitive reframing of the same problem changes judgments.',
      keywords: 'conjunction fallacy, probability judgment, heuristics, representativeness, HUMMBL:P, HUMMBL:IN',
      nist_functions: 'MEASURE',
    },
    {
      file: 'T13_reasoning.bib',
      type: 'book',
      key: 'JohnsonLaird1983MentalModels',
      title: 'Mental Models: Toward a Cognitive Science of Language, Inference, and Consciousness',
      author: 'Johnson-Laird, Philip N.',
      year: '1983',
      publisher: 'Harvard University Press',
      address: 'Cambridge, MA',
      isbn: '9780674568828',
      abstract: 'Johnson-Laird proposes that human reasoning operates not on formal logic or syntactic rules, but on mental models — internal representations of the world that capture the structure of situations. The theory explains how people draw conclusions by constructing, evaluating, and manipulating models of premises. It accounts for systematic reasoning errors as limitations in working memory capacity for model construction, not as logical failures. The framework unifies language understanding, deduction, induction, and consciousness under a single representational architecture, grounding HUMMBL Perspective (P) and Synthesis (SY) operators in the cognitive science of mental representation.',
      keywords: 'mental models, reasoning, cognitive science, inference, consciousness, HUMMBL:P, HUMMBL:SY',
    },
    {
      file: 'T13_reasoning.bib',
      type: 'book',
      key: 'Oaksford2007BayesianRationality',
      title: 'Bayesian Rationality: The Probabilistic Approach to Human Reasoning',
      author: 'Oaksford, Mike and Chater, Nick',
      year: '2007',
      publisher: 'Oxford University Press',
      address: 'Oxford, UK',
      isbn: '9780198524496',
      abstract: 'Oaksford and Chater argue that human reasoning is not fundamentally logical but probabilistic — governed by Bayesian principles rather than formal deductive logic. They reinterpret classical reasoning tasks (Wason selection task, syllogistic reasoning) as optimal Bayesian inference under uncertainty, showing that apparent "errors" in human reasoning are actually rational responses given the probabilistic structure of the environment. This paradigm shift from logic to probability as the framework for human rationality grounds HUMMBL Perspective (P) and Inversion (IN) operators by reframing the rationality debate itself.',
      keywords: 'Bayesian reasoning, rationality, probability, cognitive science, HUMMBL:P, HUMMBL:IN',
    },
    {
      file: 'T13_reasoning.bib',
      type: 'book',
      key: 'Gigerenzer2007GutFeelings',
      title: 'Gut Feelings: The Intelligence of the Unconscious',
      author: 'Gigerenzer, Gerd',
      year: '2007',
      publisher: 'Viking',
      address: 'New York, NY',
      isbn: '9780670038633',
      abstract: 'Gigerenzer presents the case that unconscious intuitions — "gut feelings" — are not irrational impulses but adaptive cognitive strategies shaped by evolution. He introduces fast-and-frugal heuristics that exploit environmental structure to make better decisions than complex rational analysis in many real-world situations. The recognition heuristic, the take-the-best heuristic, and the gaze heuristic demonstrate that less information can lead to better decisions. This challenges the heuristics-and-biases tradition by showing that heuristics are not biases but rational adaptations, grounding HUMMBL Perspective (P) and Inversion (IN) operators in the ecological rationality framework.',
      keywords: 'heuristics, intuition, ecological rationality, decision making, HUMMBL:P, HUMMBL:IN',
    },
    {
      file: 'T13_reasoning.bib',
      type: 'book',
      key: 'Thagard2000Coherence',
      title: 'Coherence in Thought and Action',
      author: 'Thagard, Paul',
      year: '2000',
      publisher: 'MIT Press',
      address: 'Cambridge, MA',
      isbn: '9780262201316',
      abstract: 'Thagard develops a unified theory of coherence as the central principle governing human thought and action. He proposes that reasoning, explanation, deliberation, and ethical judgment all operate through constraint satisfaction — maximizing coherence among beliefs, goals, and actions. The theory integrates epistemology, ethics, and cognitive science under a computational framework where coherence is formally defined as constraint satisfaction. This synthesis of diverse cognitive domains under a single principle grounds HUMMBL Synthesis (SY) and Perspective (P) operators in a formal theory of cognitive integration.',
      keywords: 'coherence, constraint satisfaction, epistemology, ethics, cognitive science, HUMMBL:SY, HUMMBL:P',
    },
    {
      file: 'T13_reasoning.bib',
      type: 'book',
      key: 'Holyoak1995MentalLeaps',
      title: 'Mental Leaps: Analogy in Creative Thought',
      author: 'Holyoak, Keith J. and Thagard, Paul',
      year: '1995',
      publisher: 'MIT Press',
      address: 'Cambridge, MA',
      isbn: '9780262082315',
      abstract: 'Holyoak and Thagard present analogy as a fundamental mechanism of human cognition, enabling creative thought through the transfer of relational structure from a familiar source domain to a novel target domain. They develop the multiconstraint theory of analogy, identifying three constraints — similarity, structure, and purpose — that govern analogical reasoning. The book traces analogy from scientific discovery (Rutherford atom, Darwin evolution) to everyday problem-solving and legal reasoning, demonstrating that analogical thinking is not a peripheral rhetorical device but a core cognitive process. Grounds HUMMBL Perspective (P), Synthesis (SY), and Recursion (RE) operators in the cognitive science of analogical reasoning.',
      keywords: 'analogy, creative thought, relational reasoning, cognitive science, HUMMBL:P, HUMMBL:SY, HUMMBL:RE',
    },
    {
      file: 'T13_reasoning.bib',
      type: 'book',
      key: 'Sloman2005CausalModels',
      title: 'Causal Models: How People Think About the World and Its Alternatives',
      author: 'Sloman, Steven A.',
      year: '2005',
      publisher: 'Oxford University Press',
      address: 'Oxford, UK',
      isbn: '9780195183115',
      abstract: 'Sloman argues that human cognition is fundamentally causal model-based: people reason about the world by constructing mental models of causal relationships, not by tracking statistical correlations. The book presents evidence that causal models enable counterfactual reasoning, intervention prediction, and explanation — capabilities that go beyond what associative learning can provide. The distinction between causal and statistical reasoning explains systematic deviations from normative probability judgments and provides a framework for understanding how people reason about what could have been. Grounds HUMMBL Perspective (P) and Decomposition (DE) operators in the cognitive science of causal representation.',
      keywords: 'causal models, counterfactual reasoning, cognitive science, causal cognition, HUMMBL:P, HUMMBL:DE',
    },
    {
      file: 'T13_reasoning.bib',
      type: 'article',
      key: 'Tenenbaum2011GrowMind',
      title: 'How to Grow a Mind: Statistics, Structure, and Abstraction',
      author: 'Tenenbaum, Joshua B. and Kemp, Charles and Griffiths, Thomas L. and Goodman, Noah D.',
      year: '2011',
      journal: 'Science',
      volume: '331',
      number: '6022',
      pages: '1279--1285',
      doi: '10.1126/science.1197557',
      abstract: 'Tenenbaum and colleagues argue that human cognition learns structured representations from sparse data through Bayesian inference over hierarchical generative models. They present a computational framework where the mind grows by inferring the latent structure of the world — from object categories to social relationships to physical causality — using probabilistic inference that balances fit with simplicity. The theory explains how children learn from single examples, how experts abstract principles from specific cases, and how the mind builds causal models that support counterfactual reasoning. Grounds HUMMBL Perspective (P) and Recursion (RE) operators in the Bayesian program of cognitive development.',
      keywords: 'Bayesian cognition, learning, abstraction, hierarchical models, cognitive development, HUMMBL:P, HUMMBL:RE',
    },
  ],
};

export const wave6T12 = {
  id: 'wave6-t12',
  description: 'T12 Complexity: strengthen P tag (+3 entries)',
  commit_msg: 'feat(bib): Wave 6 — add 3 complexity entries strengthening P tag in T12',
  entries: [
    {
      file: 'T12_complexity.bib',
      type: 'book',
      key: 'Mitchell2009Complexity',
      title: 'Complexity: A Guided Tour',
      author: 'Mitchell, Melanie',
      year: '2009',
      publisher: 'Oxford University Press',
      address: 'Oxford, UK',
      isbn: '9780195124415',
      abstract: 'Mitchell provides an accessible survey of complexity science — the study of systems with many interacting parts that produce emergent collective behavior. The book covers chaos, fractals, genetic algorithms, cellular automata, self-organizing systems, and network science, tracing the field from its Santa Fe Institute origins to current frontiers. Mitchell critically examines whether complexity science constitutes a genuine scientific revolution or a collection of metaphorical tools, offering a balanced perspective on the field achievements and limitations. The tour through multiple perspectives on complexity — from information theory to evolutionary computation — grounds HUMMBL Perspective (P) and Synthesis (SY) operators in the complexity science tradition.',
      keywords: 'complexity science, emergence, chaos, genetic algorithms, networks, HUMMBL:P, HUMMBL:SY',
    },
    {
      file: 'T12_complexity.bib',
      type: 'book',
      key: 'BarYam1997Dynamics',
      title: 'Dynamics of Complex Systems',
      author: 'Bar-Yam, Yaneer',
      year: '1997',
      publisher: 'Perseus Books',
      address: 'Reading, MA',
      isbn: '9780738201294',
      abstract: 'Bar-Yam presents a comprehensive mathematical framework for analyzing complex systems, unifying concepts from nonlinear dynamics, chaos theory, statistical mechanics, and information theory. The text develops formal tools for studying emergent behavior in systems ranging from neural networks to ecosystems to social organizations, with emphasis on how microscopic interactions produce macroscopic patterns. The framework introduces multiscale analysis as a key methodology for understanding complexity — how system behavior changes across levels of description. Grounds HUMMBL Decomposition (DE) and Synthesis (SY) operators in the formal mathematical tradition of complex systems science.',
      keywords: 'complex systems, nonlinear dynamics, emergence, multiscale analysis, HUMMBL:DE, HUMMBL:SY',
    },
    {
      file: 'T12_complexity.bib',
      type: 'book',
      key: 'Ladyman2007EverythingMustGo',
      title: 'Every Thing Must Go: Metaphysics Naturalized',
      author: 'Ladyman, James and Ross, David and Spurrett, David and Collier, John',
      year: '2007',
      publisher: 'Oxford University Press',
      address: 'Oxford, UK',
      isbn: '9780199274196',
      abstract: 'Ladyman and colleagues argue that metaphysics must be naturalized — grounded in actual science rather than a priori reasoning. They develop a scale-relative ontology for complex systems, proposing that reality is structured by real patterns at multiple levels of organization, with no privileged fundamental level. The book applies complexity science to philosophy, arguing that emergent properties are real causal agents at their own scale and cannot be reduced to physics alone. This naturalistic metaphysics provides a philosophical foundation for HUMMBL Perspective (P) and Synthesis (SY) operators by grounding multi-level analysis in a rigorous ontological framework.',
      keywords: 'naturalized metaphysics, complexity, emergence, scale-relative ontology, HUMMBL:P, HUMMBL:SY',
    },
  ],
};

export const wave6T7 = {
  id: 'wave6-t7',
  description: 'T7 Emerging: strengthen IN and P tags (+2 entries)',
  commit_msg: 'feat(bib): Wave 6 — add 2 emerging-tech entries strengthening IN/P tags in T7',
  entries: [
    {
      file: 'T7_emerging.bib',
      type: 'book',
      key: 'Christian2020Alignment',
      title: 'The Alignment Problem: Machine Learning and Where It Can Go Wrong',
      author: 'Christian, Brian',
      year: '2020',
      publisher: 'W.W. Norton and Company',
      address: 'New York, NY',
      isbn: '9780393635793',
      abstract: 'Christian surveys the alignment problem — the challenge of ensuring that machine learning systems pursue the goals their designers intend rather than misaligned proxies. The book traces alignment failures from early reward hacking to contemporary concerns about large language models, covering inverse reinforcement learning, preference learning, and human feedback approaches. Christian frames alignment as fundamentally a problem of human values, cognitive science, and philosophy, not just engineering, connecting technical ML research to deeper questions about what we want systems to do and how we communicate intent. Grounds HUMMBL Inversion (IN), Perspective (P), and Decomposition (DE) operators in the alignment literature.',
      keywords: 'alignment, machine learning, reward hacking, inverse reinforcement learning, values, HUMMBL:IN, HUMMBL:P, HUMMBL:DE',
      nist_functions: 'MEASURE, MANAGE',
    },
    {
      file: 'T7_emerging.bib',
      type: 'book',
      key: 'Crawford2021AtlasAI',
      title: 'Atlas of AI: Power, Politics, and the Planetary Costs of Artificial Intelligence',
      author: 'Crawford, Kate',
      year: '2021',
      publisher: 'Yale University Press',
      address: 'New Haven, CT',
      isbn: '9780300209570',
      abstract: 'Crawford maps the hidden infrastructure of artificial intelligence, revealing the material, labor, and environmental costs that underlie AI systems. From lithium mines in the Atacama to data annotation work camps in Kenya, she traces the supply chains that make AI possible, challenging the framing of AI as immaterial and autonomous. The book argues that AI is neither artificial nor intelligent in isolation — it is deeply embedded in human labor, environmental extraction, and political power structures. This inversion of the standard AI narrative grounds HUMMBL Perspective (P), Inversion (IN), and Decomposition (DE) operators in a critical materialist analysis of AI.',
      keywords: 'AI ethics, material infrastructure, labor, environment, power, HUMMBL:P, HUMMBL:IN, HUMMBL:DE',
      nist_functions: 'GOVERN, MEASURE',
    },
  ],
};
