// entries-wave2a.mjs — 8 CO-grounding entries
export const wave2a = {
  id: 'wave2a-co',
  description: 'CO-grounding entries for Composition operator',
  commit_msg: 'feat(bib): add 8 CO-grounding entries (Wave 2A expansion plan)\n\nAdd 8 entries grounding the Composition (CO) transformation across\nT3, T5, T9, T12. Total entries: 365 -> 373.\n\nNew entries:\n- Holland1998Emergence (T12): emergence theory, constrained generating procedures\n- Anderson1972MoreIsDifferent (T12): broken symmetry, composition changes behavior\n- Simon1962Architecture (T5): near-decomposability, hierarchical composition\n- Alexander1979TimelessBuilding (T3): pattern language, compositional design\n- Gamma1994DesignPatterns (T5): pattern composition in software\n- Arthur2009Technology (T3): combinatorial evolution of technology\n- Page2017Diversity (T12): diversity prediction theorem\n- Frenken2006Innovation (T9): recombinant innovation, NK model\n\nValidation: 0 warnings, 0 errors, 0 duplicates, 100/100 tests pass.',
  entries: [
    {
      file: 'T12_complexity.bib', type: 'book', key: 'Holland1998Emergence',
      title: 'Emergence: From Chaos to Order', author: 'Holland, John H.', year: '1998',
      publisher: 'Addison-Wesley', address: 'Reading, MA', isbn: '9780201149432',
      doi_unavailable: 'Addison-Wesley trade book; no DOI assigned',
      abstract: 'Holland presents a theory of emergence -- how complex systems produce behaviors that cannot be predicted from the properties of their individual components. Drawing on games like chess, neural networks, and ecosystems, Holland identifies the conditions under which emergent behavior arises: a small number of rules or laws that generate significant complexity through their interaction. He introduces constrained generating procedures (CGPs) as a formal framework for modeling emergent systems, where the composition of simple mechanisms produces systems with qualitatively new properties. The book distinguishes emergence from mere complication: a system is emergent when its behavior cannot be deduced from inspecting its components in isolation. For HUMMBL, Holland\'s framework grounds the CO (Composition) transformation: the central question of composition is not just how to combine components but understanding when and why combinations produce emergent properties that exceed the sum of their parts. The CGP formalism provides a computational basis for the CO operator\'s integration scoring.',
      keywords: 'emergence, complex systems, constrained generating procedures, self-organization, HUMMBL:CO, HUMMBL:SY, HUMMBL:DE',
    },
    {
      file: 'T12_complexity.bib', type: 'article', key: 'Anderson1972MoreIsDifferent',
      title: 'More Is Different: Broken Symmetry and the Nature of the Hierarchical Structure of Science',
      author: 'Anderson, Philip W.', year: '1972', journal: 'Science', volume: '177', number: '4047', pages: '393--396',
      doi: '10.1126/science.177.4047.393',
      abstract: 'Anderson\'s seminal essay argues that reductionism is insufficient for understanding nature. At each level of complexity, entirely new properties emerge that cannot be deduced from the lower level, even with complete knowledge of the lower-level laws. A symmetry that holds at one scale is broken at a higher scale, producing qualitatively new behavior. Anderson traces this from particle physics through chemistry, biology, and psychology, showing that each level has its own fundamental laws that are not derivable from the level below. For HUMMBL, Anderson\'s argument is the foundational justification for the CO (Composition) transformation: composition is not merely aggregation but a symmetry-breaking operation that produces new properties. The CO operator must recognize that combining components creates a new level of organization with its own laws -- laws that cannot be predicted by analyzing the components in isolation.',
      keywords: 'emergence, broken symmetry, reductionism, hierarchy, complexity, HUMMBL:CO, HUMMBL:DE, HUMMBL:SY',
    },
    {
      file: 'T5_engineering.bib', type: 'article', key: 'Simon1962Architecture',
      title: 'The Architecture of Complexity', author: 'Simon, Herbert A.', year: '1962',
      journal: 'Proceedings of the American Philosophical Society', volume: '106', number: '6', pages: '467--482',
      doi_unavailable: 'American Philosophical Society proceedings from 1962; no DOI assigned',
      abstract: 'Simon argues that complex systems are nearly always hierarchical -- composed of interrelated subsystems, each of which is itself hierarchical. He introduces near-decomposability: in a nearly decomposable system, the interactions among subsystems are weak but not negligible. The short-run behavior of each subsystem is approximately independent of the others, while the long-run behavior depends only weakly on the others. Simon demonstrates that hierarchic systems evolve more rapidly than non-hierarchic systems of comparable size, because stable intermediate forms accelerate the evolutionary process. He uses the watchmakers Hora and Tempus as a parable: Hora assembles watches in subassemblies that can be put down without breaking, while Tempus assembles each watch as a single unit. For HUMMBL, Simon\'s near-decomposability is a foundational principle for the CO (Composition) transformation: effective compositions are hierarchically structured with weak inter-subsystem coupling.',
      keywords: 'hierarchy, near-decomposability, complex systems, architecture, evolution, HUMMBL:CO, HUMMBL:DE, HUMMBL:SY',
    },
    {
      file: 'T3_applied.bib', type: 'book', key: 'Alexander1979TimelessBuilding',
      title: 'The Timeless Way of Building', author: 'Alexander, Christopher', year: '1979',
      publisher: 'Oxford University Press', address: 'New York', isbn: '9780195024029',
      doi_unavailable: 'Oxford University Press trade book; no DOI assigned',
      abstract: 'Alexander introduces the concept of the quality without a name -- a fundamental property of good architecture that emerges from the pattern of relationships among elements. He argues that buildings become alive through pattern languages -- shared vocabularies of design patterns that compose into coherent wholes. Each pattern describes a recurring problem and its solution in context, and patterns connect to other patterns to form a language. The composition of patterns is not mechanical but generative: each pattern creates the context for others, and the whole emerges from the interaction. For HUMMBL, Alexander\'s pattern language is a foundational model for the CO (Composition) transformation: composition as the generative interconnection of patterns, where the quality of the whole depends not on the quality of individual parts but on the pattern of their relationships.',
      keywords: 'pattern language, architecture, design, composition, quality, HUMMBL:CO, HUMMBL:DE, HUMMBL:SY',
    },
    {
      file: 'T5_engineering.bib', type: 'book', key: 'Gamma1994DesignPatterns',
      title: 'Design Patterns: Elements of Reusable Object-Oriented Software',
      author: 'Gamma, Erich and Helm, Richard and Johnson, Ralph and Vlissides, John', year: '1994',
      publisher: 'Addison-Wesley', address: 'Reading, MA', isbn: '9780201633610',
      doi_unavailable: 'Addison-Wesley trade book; no DOI assigned',
      abstract: 'The Gang of Four\'s seminal work catalogs 23 design patterns for object-oriented software, organized into creational, structural, and behavioral categories. Each pattern names a recurring design problem, describes its solution, and identifies consequences. Key patterns include Adapter (composing incompatible interfaces), Composite (treating individual objects and compositions uniformly), Observer (one-to-many notification), and Strategy (interchangeable algorithms). The book\'s central insight is that good software design is fundamentally about composition: not just writing new code but combining existing components in patterns that produce desired properties. For HUMMBL, the Design Patterns catalog is a concrete, practitioner-grounded model for the CO (Composition) transformation: each pattern is a named composition strategy with known properties and trade-offs. The structural/behavioral distinction maps to HUMMBL\'s separation of static composition from dynamic composition.',
      keywords: 'design patterns, object-oriented, software engineering, composition, HUMMBL:CO, HUMMBL:DE, HUMMBL:SY',
    },
    {
      file: 'T3_applied.bib', type: 'book', key: 'Arthur2009Technology',
      title: 'The Nature of Technology: What It Is and How It Evolves',
      author: 'Arthur, W. Brian', year: '2009', publisher: 'Free Press', address: 'New York', isbn: '9781416544067',
      doi_unavailable: 'Free Press trade book; no DOI assigned',
      abstract: 'Arthur argues that all technologies are combinations of pre-existing technologies -- a recursive, combinatorial process where each new technology becomes a building block for future technologies. This explains the exponential character of technological progress: as the number of available components grows, the number of possible combinations grows combinatorially. Innovation occurs through recombination of existing components, discovery of new principles, and repurposing of existing technologies to new domains. The book challenges the linear model of innovation, showing that technology evolves through a branching, recursive process more like biological evolution than engineering design. For HUMMBL, Arthur\'s combinatorial theory is a foundational model for the CO (Composition) transformation: composition as the primary engine of innovation, where the value of a new combination depends on the affordances of its components and the creativity of their interconnection.',
      keywords: 'technology, combinatorial evolution, innovation, recombination, HUMMBL:CO, HUMMBL:RE, HUMMBL:SY',
    },
    {
      file: 'T12_complexity.bib', type: 'book', key: 'Page2017Diversity',
      title: 'The Diversity Bonus: How Great Teams Pay Off in the Knowledge Economy',
      author: 'Page, Scott E.', year: '2017', publisher: 'Princeton University Press', address: 'Princeton, NJ', isbn: '9780691175368',
      doi_unavailable: 'Princeton University Press trade book; no DOI assigned',
      abstract: 'Page formalizes the Diversity Prediction Theorem: the collective error of a group equals the average individual error minus the diversity of the group. This mathematical result shows that diversity is not merely a social good but a cognitive asset -- a diverse group of less-capable individuals can outperform a homogeneous group of more-capable individuals because their different perspectives cancel out individual biases. Page identifies cognitive diversity (different mental models) and identity diversity (different backgrounds) as two types, with cognitive diversity producing the prediction bonus. The book distinguishes between diverse crowds (independent predictions) and diverse teams (interactive collaboration). For HUMMBL, Page\'s theorem is a foundational result for the CO (Composition) transformation: the value of composition depends on the diversity of the components being combined. The CO operator should prefer composing diverse models over similar ones.',
      keywords: 'diversity, prediction theorem, collective intelligence, cognitive diversity, HUMMBL:CO, HUMMBL:IN, HUMMBL:SY',
    },
    {
      file: 'T9_economics.bib', type: 'article', key: 'Frenken2006Innovation',
      title: 'Technological Innovation and Complexity Theory',
      author: 'Frenken, Koen', year: '2006',
      journal: 'Economics of Innovation and New Technology', volume: '15', number: '2', pages: '137--155',
      doi: '10.1080/10438590500141189',
      abstract: 'Frenken applies complexity theory to the economics of innovation, arguing that technological progress is driven by recombinant innovation -- the creation of new technologies by combining existing ones in novel ways. Drawing on Kauffman\'s NK model, Frenken models the innovation landscape as a fitness landscape where the value of a combination depends on interdependencies among its components. The paper introduces modular innovation: when technologies are decomposable into modules, innovation can proceed by replacing individual modules rather than redesigning the entire system. The optimal level of modularity depends on the ruggedness of the fitness landscape: in smooth landscapes, tightly coupled systems perform better; in rugged landscapes, modular systems are more adaptable. For HUMMBL, Frenken\'s framework connects the CO (Composition) transformation to economic theory: composition is the engine of economic growth. The modularity insight is directly applicable -- the CO operator should prefer modular compositions when the problem landscape is uncertain.',
      keywords: 'recombinant innovation, modularity, NK model, fitness landscape, HUMMBL:CO, HUMMBL:DE, HUMMBL:RE',
    },
  ],
};
